apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-nginx-pool
  namespace: metallb-system
spec:
  addresses:
    - "{{ include "ingress-nginx.ipaddresspool.address" . }}"
  autoAssign: false
